### ISSUE TITLE
Feature Request: Derive PartialEq

### ISSUE THREAD

**Issue by brycefisher** [lovasoa/custom_error#12]
Currently, the `custom_error` macro derives only the `Debug` trait. However, its impossible to directly compare any two Error type produced by `custom_error!` since this relies on `PartialEq`. This would make testing more natural.

**Comment by lovasoa** [comment]
This looks convenient, but I am not sure this can be done easily. What would we do if an error had a parameter that does not implement `PartialEq` ?

**Comment by brycefisher** [comment]
Right! Good point.

I'm not actually sure how to accomplish this using concrete types. I would use trait bounds to create a conditional impl...

I think there's a few possibilities for getting a PartialEq impl here:

 1. use procedural macros to conditionally derive PartialEq -- I would not recommend this approach. It feels too heavyweight, but I don't really know how to implement a procedural macro. 
 2. Provide a PartialEq impl that only operates on variants used in the macro. This would not be able to discriminate between fields within a variant, but could be implemented regardless.
 3. Provide a new macro which allows one to specify which derives one wants. I could imagine serde, diesel, and many other derives would be desirable. If any derive cannot be satisfied, the user should be able to figure this out and could remove the offending trait. Pseudo code: `custom_error_derive!(#[derive(PartialEq)] pub FooError ... );`
 4. Add a new syntax to the existing macro so that a list of derives could be specified by the user. Pseudo code: `custom_error!(#[derive(PartialEq)] pub FooError ... );`. It should be possible to keep a different top level pattern which omits the derives so that this is a nonbreaking change.

I would lean towards 4 because it provides maximum flexibility with minimum change.

What do you think?

**Comment by brycefisher** [comment]
Bumped into this again today :-(

I immediately started asking myself the question you asked, then looked through the source code and then noticed I already filled this issue. Woot!

Yeah, I wonder about allowing the user to provide a list of derives (optionally) to the macro. I'm not very good at writing macros, but I _think_ this is theoretically possible -- though possibly not with my syntax above.

**Comment by lovasoa** [comment]
Yes, it looks possible. Do you want to try and make a pull request?

**Comment by lovasoa** [comment]
OK, I had a look at this in the morning. Your proposition number 4 seems to  just work :) So I'm going to implement this and make a new release.

**Comment by lovasoa** [comment]
I implemented it, and released a new version ([1.5.0](https://crates.io/crates/custom_error/1.5.0)) to crates.io.

You can now write

```rust
custom_error!{
    #[derive(PartialEq,PartialOrd)]
    MyError
        A="error a",
        B="error b"
}

assert_eq!(MyError::A, MyError::A);
assert!(MyError::A < MyError::B);

```

**Comment by brycefisher** [comment]
I think you are the most positive and responsive maintainer I've ever
interacted with. You set the bar high for the rest of us!

**Comment by lovasoa** [comment]
Thank you ! :)
