### ISSUE TITLE
function

### ISSUE THREAD

**Issue by ami44** [lovasoa/custom_error#2]
Bonjour

Est-ce qu'il serait possible d'écrire ceci ?

```rust
fn complexString(code: u8) -> String {
    "unknown error with code {code}."
}
custom_error!(MyError
    Unknown{code:u8} = complexString(code),
    Err41            = "Sit by a lake"
);
```

Cdlt

**Comment by ami44** [comment]
Bonjour @iovasoa.

Je suis a la recherche de messages dynamiques pour plusieurs cas:
- afficher le message en fr/en/etc selon une variable global lang par exemple
- afficher un message différent en mode debug/integration/production ...


Je ferme cette issue (je te laisse libre de la réouvrir bien sur) car je suis désormais passé à https://github.com/rust-lang-nursery/failure (notamment pour afficher les erreurs en cascade (aka context)).

Cordialement
Alban

**Comment by lovasoa** [comment]
Je rouvre cette issue parce que c'est un cas intéressant. Malheureusement, la syntaxe 

```rust
    Unknown{code:u8} = complexString(code),
```

n'est pas possible, parce qu'il y a une ambiguïté. Il n'est pas possible pour la macro de faire la différence entre un appel de fonction et une autre expression.

Par contre, je propose la syntaxe suivante : 

```rust
    Unknown{code:u8} = @{ some rust code }
```

C'est plus général, car on peut appeler une fonction, mais aussi faire le calcul directement. 

On pourrait par exemple écrire

```rust
    Unknown{code:u8} = @{ complexString(code) },
```

**Comment by ami44** [comment]
je n'avais pas compris le pourquoi de la difficulté mais avec le recul je comprend ta solution.
Bonne idée !
