### ISSUE TITLE
Make the library compile with no_std

### ISSUE THREAD

**Issue by gz** [lovasoa/custom_error#25]
Hi, this is a pretty useful library -- thanks. 

I'm using it in a no-std environment but had to make some small changes to this crate so it compiles. 
Would you be willing to accept a pull-request that makes the library compile for no-std too?

The "biggest hurdle", aside from changing some import paths from `std::` to `core::`, is that the Error trait is defined in std (but, this likely will go back into core again in the future https://doc.rust-lang.org/nightly/src/std/error.rs.html#5). So for the no_std environment what I do right now is that custom_error provides the Error trait.

**Comment by lovasoa** [comment]
Yes, I would happily welcome such a PR ! We can add a no-std crate feature that provides an error trait.
