### ISSUE TITLE
Feature Request: Access `source` value in Display string

### ISSUE THREAD

**Issue by brycefisher** [lovasoa/custom_error#4]
## Existing Limitation

Currently, if I leverage the `source` keyword for automatic conversion from another error type, I can't access the value of the source error.

## Proposed Change

I'd love to be able to use the source error in the format string for the Display impl. 

## Motivation

In many situations, the lower level error I'm trying to wrap should be bubbled up as different "semantic" errors. For instance, in a function with operates on a file and tries to parse its content, I'd potentially want to provide different help text for parse errors, file permissions errors, and file not existing differently. However both file permissions and file not found errors are going to be `std::io::Error` types most likely. 

### Example Syntax

```rs
use std::io;

custom_error!{ScriptError
    io{source: io::Error} = "IO Error occurred: {source.kind()}"
}

fn script() -> Result<(), ScriptError> {
   Err(ScriptError::io(io::Error::new(
        io::ErrorKind::AddrInUse,
         "0.0.0.0:8080"
    )))
}

println("{}", script());
// IO Error occurred: AddrInUse
```

## Alternatives

 1. I could created nested error types. This would increase the amount of boilerplate, but keeps `custom_error` crate simpler. It could already be done today.
 2. I could have a variant of my custom error which doesn't have the conversion implemented by the macro and do that conversion myself. This could already be done today, but again seems to increase the boilerplate.

**Comment by lovasoa** [comment]
Hello @brycefisher!

Thank you for the nice feature request.

 In #2, @ami44 proposed a new syntax to create custom error messages using a simple rust function. Do you think this would be enough to solve this, or would you still consider it too much boilerplate ?

The problem here is not that you cannot access `source` (you can). It's that you can only use the parameters as is (`source` is ok, `source.kind()` is not)

**Comment by lovasoa** [comment]
You can now write:

```rust
        custom_error! {MyError
            Io{source:io::Error} = @{format!("IO Error occurred: {:?}", source.kind())}
        }
```

**Comment by brycefisher** [comment]
Amazing!! Thank you so much @lovasoa !

**Comment by lovasoa** [comment]
You're welcome :)
