### ISSUE TITLE
Feature Request: Allow trailing comma in list of error variants

### ISSUE THREAD

**Issue by brycefisher** [lovasoa/custom_error#5]
This is a small feature request for a style nit. Personally, I like to use trailing commas so that VCS deltas don't include unnecessary changes for reviewers to look at.

However, currently the macro fails when I use a comma after the last variant.

Additionally, the error message that `rustc` emits is a bit confusing (ex: "There's no `)` anywhere in that code!").

```sh
error: no rules expected the token `(`
  --> src/domains/account/mod.rs:30:1
   |
30 | / custom_error!{pub AccountError
31 | |     EmptyName                       = "No name was provided when trying to create an account",
32 | |     DatabaseError{source: SqlError} = "A database error occurred trying to run database command",
33 | |     DoesNotExist                    = "Account does not exist",
34 | |     DataCorruption                  = "The account table is in an inconsistent state",
35 | | }
   | |_^ no rules expected the token `(`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

This error isn't anything to do with `custom_error` per se, but I bump into it often. I'd hazard a guess that other users newer to Rust would be scared off by this experience. Supporting trailing commas would just make this papercut disappear :-)

**Comment by lovasoa** [comment]
Thank you for the report @brycefisher ! I added support for trailing commas. It will be in version `1.3.0`.
