### ISSUE TITLE
Lifetimes and error types

### ISSUE THREAD

**Issue by petoknm** [lovasoa/custom_error#7]
I am trying to wrap a nom::Err which requires a lifetime parameter.

```
type NomError<'a> = nom::Err<&'a [u8]>;

custom_error!{Error<'a>
    Parser{source: NomError<'a>} = "Parser error",
    Fmt{source: std::fmt::Error} = "Formatting error"
}
```

but I get an error: `no rules expected the token 'a`.
It would be nice if got this to work :)

**Comment by lovasoa** [comment]
I am going to have a look at how this could be done.

**Comment by lovasoa** [comment]
In fact, the source of an error [has to be `'static`](https://doc.rust-lang.org/std/error/trait.Error.html#method.source)... We could implement `From` without implementing `source()`, but it wouldn't be really nice...

**Comment by petoknm** [comment]
I think it might be because not all variants of my error require that lifetime... It works when I have just one variant (the one that requires the lifetime) but when I add another variant (one that has a source that doesnt need the lifetime) it says `undeclared lifetime 'a`

**Comment by petoknm** [comment]
something like this -> #8

**Comment by lovasoa** [comment]
I think I found the bug. The lifetime parameters [given to the `impl` block](https://github.com/lovasoa/custom_error/blob/lifetime_params/src/lib.rs#L234) of error conversion should be all those of the type we are constructing, not only those of the variant for which the conversion is implemented.

**Comment by lovasoa** [comment]
I fixed the bug, and added a new test. You can test it, contribute new tests, and if everything goas well, I will merge the new branch into master and release a new version.

**Comment by petoknm** [comment]
Yey, now it works!

**Comment by lovasoa** [comment]
Let's close the issue when we merge the branch. I would really like to be sure we did not introduce bugs.
